apiVersion: v1
kind: List
items:
  - apiVersion: serving.knative.dev/v1
    kind: Service
    spec:
      template:
        metadata:
          labels:
            name: redhat-airline-flight-api
            appId: ba1plp46e52k
        spec:
          containers:
            - image: >-
                image-registry.openshift-image-registry.svc:5000/redhat-airline-serverless/redhat-airline-flight-api
    metadata:
      name: redhat-airline-flight-api
      namespace: redhat-airline-serverless
